apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - args:
        - --server_address=0.0.0.0:8080
        env:
        - name: MICRO_SELECTOR
          value: static
        - name: MICRO_TRANSPORT
          value: grpc
        image: hanamichi/hal9000-srv:k8s
        imagePullPolicy: IfNotPresent
        name: greeter
        ports:
        - containerPort: 8080
          name: grpc
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeter
  name: greeter
spec:
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: greeter
  type: ClusterIP
