apiVersion: apps/v1
kind: Deployment
metadata:
  name: hal9000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal9000
  template:
    metadata:
      labels:
        app: hal9000
    spec:
      containers:
        - name: hal9000
          env:
            - name: MICRO_SELECTOR
              value: static
          imagePullPolicy: IfNotPresent
          args:
            - --server_address=0.0.0.0:8080
          image: hanamichi/hal9000-srv:k8s
          ports:
            - containerPort: 8080
              name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: hal9000
  labels:
    app: hal9000
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: grpc
  selector:
    app: hal9000