apiVersion: apps/v1
kind: Deployment
metadata:
  name: hal9000-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal9000-api
  template:
    metadata:
      labels:
        app: hal9000-api
    spec:
      containers:
        - name: hal9000-api
          env:
            name: MICRO_SELECTOR
            value: static
          imagePullPolicy: IfNotPresent
          args:
            - --server_address=0.0.0.0:8080
          image: hanamichi/hal9000-api:k8s
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: hal9000-api
  labels:
    app: hal9000-api
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: hal9000-api