// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// user id, user belong to different group and role, has different permissions
	UserId *wrappers.StringValue `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// user name
	Username *wrappers.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// user email
	Email *wrappers.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// user phone number
	PhoneNumber *wrappers.StringValue `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// user description
	Description *wrappers.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// user creator
	Creator *wrappers.StringValue `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	// user status eg.[0|1]
	Status *wrappers.Int32Value `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	// the time when user create
	CreateTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// the time when user update
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// user roles
	Roles                []*UserRole `protobuf:"bytes,10,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *User) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *User) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetPhoneNumber() *wrappers.StringValue {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *User) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *User) GetCreator() *wrappers.StringValue {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *User) GetStatus() *wrappers.Int32Value {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *User) GetRoles() []*UserRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UserRole struct {
	// user role name
	RoleName             string   `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type DescribeUsersRequest struct {
	// query key, support these fields(user_id, email, phone_number, status)
	SearchWord *wrappers.StringValue `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word,omitempty"`
	// sort key, order by sort_key, default create_time
	SortKey *wrappers.StringValue `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	// value = 0 sort ASC, value = 1 sort DESC
	Reverse *wrappers.BoolValue `protobuf:"bytes,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	// data limit, default 20, max 200
	Limit uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// data offset, default 0
	Offset uint32 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	// use root group ids to get all group ids
	RootGroupId []string `protobuf:"bytes,6,rep,name=root_group_id,json=rootGroupId,proto3" json:"root_group_id,omitempty"`
	// group ids
	GroupId []string `protobuf:"bytes,7,rep,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// user ids
	UserId []string `protobuf:"bytes,8,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// status eg.[active|deleted]
	Status []string `protobuf:"bytes,9,rep,name=status,proto3" json:"status,omitempty"`
	// role ids
	RoleId []string `protobuf:"bytes,10,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// username
	Username []string `protobuf:"bytes,11,rep,name=username,proto3" json:"username,omitempty"`
	// email, eg.op@yunify.com
	Email []string `protobuf:"bytes,12,rep,name=email,proto3" json:"email,omitempty"`
	// phone number, string of 11 digital
	PhoneNumber          []string `protobuf:"bytes,13,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeUsersRequest) Reset()         { *m = DescribeUsersRequest{} }
func (m *DescribeUsersRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeUsersRequest) ProtoMessage()    {}
func (*DescribeUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *DescribeUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeUsersRequest.Unmarshal(m, b)
}
func (m *DescribeUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeUsersRequest.Marshal(b, m, deterministic)
}
func (m *DescribeUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeUsersRequest.Merge(m, src)
}
func (m *DescribeUsersRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeUsersRequest.Size(m)
}
func (m *DescribeUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeUsersRequest proto.InternalMessageInfo

func (m *DescribeUsersRequest) GetSearchWord() *wrappers.StringValue {
	if m != nil {
		return m.SearchWord
	}
	return nil
}

func (m *DescribeUsersRequest) GetSortKey() *wrappers.StringValue {
	if m != nil {
		return m.SortKey
	}
	return nil
}

func (m *DescribeUsersRequest) GetReverse() *wrappers.BoolValue {
	if m != nil {
		return m.Reverse
	}
	return nil
}

func (m *DescribeUsersRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeUsersRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeUsersRequest) GetRootGroupId() []string {
	if m != nil {
		return m.RootGroupId
	}
	return nil
}

func (m *DescribeUsersRequest) GetGroupId() []string {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *DescribeUsersRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *DescribeUsersRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeUsersRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *DescribeUsersRequest) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *DescribeUsersRequest) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *DescribeUsersRequest) GetPhoneNumber() []string {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type DescribeUsersResponse struct {
	// total count of qualified user
	TotalCount uint32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// list of user
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeUsersResponse) Reset()         { *m = DescribeUsersResponse{} }
func (m *DescribeUsersResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeUsersResponse) ProtoMessage()    {}
func (*DescribeUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *DescribeUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeUsersResponse.Unmarshal(m, b)
}
func (m *DescribeUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeUsersResponse.Marshal(b, m, deterministic)
}
func (m *DescribeUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeUsersResponse.Merge(m, src)
}
func (m *DescribeUsersResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeUsersResponse.Size(m)
}
func (m *DescribeUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeUsersResponse proto.InternalMessageInfo

func (m *DescribeUsersResponse) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DescribeUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUserRequest struct {
	// user id
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FloatValue           float32  `protobuf:"fixed32,2,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserRequest) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

type CreateUserRequest struct {
	// required, user email
	Email *wrappers.StringValue `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// user phone number
	PhoneNumber *wrappers.StringValue `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// required, user password
	Password *wrappers.StringValue `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// required, user role_id
	RoleId *wrappers.StringValue `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// user description
	Description          *wrappers.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CreateUserRequest) GetPhoneNumber() *wrappers.StringValue {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *CreateUserRequest) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *CreateUserRequest) GetRoleId() *wrappers.StringValue {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *CreateUserRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

type CreateUserResponse struct {
	// id of user created
	UserId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "hal9000.User")
	proto.RegisterType((*UserRole)(nil), "hal9000.UserRole")
	proto.RegisterType((*DescribeUsersRequest)(nil), "hal9000.DescribeUsersRequest")
	proto.RegisterType((*DescribeUsersResponse)(nil), "hal9000.DescribeUsersResponse")
	proto.RegisterType((*GetUserRequest)(nil), "hal9000.GetUserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "hal9000.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "hal9000.CreateUserResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 956 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xdb, 0x6f, 0xe3, 0xc4,
	0x17, 0xc7, 0xe5, 0xa4, 0x89, 0x93, 0x71, 0xf3, 0x93, 0x3a, 0xbf, 0x76, 0x63, 0xd2, 0xbd, 0x0c,
	0xe6, 0x61, 0x8b, 0x94, 0xab, 0xbb, 0x0b, 0xbb, 0xe5, 0xa6, 0x64, 0xd1, 0x56, 0x55, 0xa5, 0x95,
	0x30, 0x97, 0x95, 0x16, 0x55, 0xd1, 0x24, 0x9e, 0x24, 0x16, 0x8e, 0xc7, 0xcc, 0x8c, 0x5b, 0xad,
	0x56, 0x95, 0x10, 0x4f, 0x88, 0xc7, 0xf0, 0x8f, 0xa1, 0xe5, 0x89, 0x17, 0x1e, 0x10, 0xfc, 0x1f,
	0x68, 0x8e, 0xed, 0x34, 0x6d, 0x41, 0x9b, 0xc2, 0x53, 0x32, 0xe7, 0x7c, 0xbf, 0xe3, 0xc9, 0x9c,
	0xcf, 0x39, 0x0e, 0xaa, 0xd1, 0xf1, 0x98, 0x27, 0x91, 0x6a, 0xc7, 0x82, 0x2b, 0x8e, 0xcd, 0x19,
	0x0d, 0x1f, 0x77, 0xbb, 0xdd, 0xc6, 0xdd, 0x29, 0xe7, 0xd3, 0x90, 0x75, 0x20, 0x3c, 0x4a, 0x26,
	0x9d, 0x33, 0x41, 0xe3, 0x98, 0x09, 0x99, 0x0a, 0x1b, 0xf7, 0xae, 0xe6, 0x55, 0x30, 0x67, 0x52,
	0xd1, 0x79, 0x9c, 0x09, 0x6e, 0x67, 0x02, 0x1a, 0x07, 0x1d, 0x1a, 0x45, 0x5c, 0x51, 0x15, 0xf0,
	0x28, 0xb7, 0x37, 0xe1, 0x63, 0xdc, 0x9a, 0xb2, 0xa8, 0x25, 0xcf, 0xe8, 0x74, 0xca, 0x44, 0x87,
	0xc7, 0xa0, 0xb8, 0xae, 0x76, 0x7e, 0xdb, 0x40, 0x1b, 0x5f, 0x4a, 0x26, 0xf0, 0x73, 0x64, 0x26,
	0x92, 0x89, 0x61, 0xe0, 0xdb, 0x06, 0x31, 0xf6, 0x2c, 0xf7, 0x76, 0x3b, 0x7d, 0x4c, 0x3b, 0x3f,
	0x47, 0xfb, 0x73, 0x25, 0x82, 0x68, 0xfa, 0x15, 0x0d, 0x13, 0x36, 0x20, 0x8b, 0xfe, 0x1d, 0x17,
	0x1c, 0x24, 0xf0, 0x0f, 0x8a, 0xbd, 0x5e, 0xef, 0xb5, 0xb1, 0x29, 0x41, 0x30, 0x3c, 0xd5, 0x0a,
	0xaf, 0xac, 0x93, 0x47, 0x3e, 0x7e, 0x84, 0x2a, 0xfa, 0x5b, 0x44, 0xe7, 0xcc, 0x2e, 0xbc, 0x79,
	0x67, 0x6f, 0xa9, 0xc6, 0x2e, 0x2a, 0xb1, 0x39, 0x0d, 0x42, 0xbb, 0xb8, 0x86, 0x2d, 0x95, 0xe2,
	0x4f, 0xd0, 0x66, 0x3c, 0xe3, 0x11, 0x1b, 0x46, 0xc9, 0x7c, 0xc4, 0x84, 0xbd, 0xb1, 0x86, 0xd5,
	0x02, 0xc7, 0x33, 0x30, 0xe0, 0x8f, 0x91, 0xe5, 0x33, 0x39, 0x16, 0x01, 0x5c, 0x99, 0x5d, 0x5a,
	0xc7, 0xbf, 0x62, 0xc0, 0xef, 0x21, 0x73, 0x2c, 0x18, 0x55, 0x5c, 0xd8, 0xe5, 0x35, 0xbc, 0xb9,
	0x18, 0xef, 0xa3, 0xb2, 0x54, 0x54, 0x25, 0xd2, 0x36, 0xc1, 0xb6, 0x7b, 0xcd, 0x76, 0x14, 0xa9,
	0x7d, 0x37, 0x75, 0x65, 0x52, 0xfc, 0x01, 0xb2, 0xc0, 0xcf, 0x86, 0x9a, 0x11, 0xbb, 0x02, 0xce,
	0xc6, 0x35, 0xe7, 0x17, 0x39, 0x40, 0x1e, 0x4a, 0xe5, 0x3a, 0xa0, 0xcd, 0x49, 0xec, 0x2f, 0xcd,
	0xd5, 0x37, 0x9b, 0x53, 0x39, 0x98, 0xef, 0xa3, 0x92, 0xe0, 0x21, 0x93, 0x36, 0x22, 0xc5, 0x3d,
	0xcb, 0xdd, 0x6a, 0x67, 0x74, 0xb7, 0x35, 0x4c, 0x1e, 0x0f, 0x99, 0x97, 0xe6, 0x9d, 0xfb, 0xa8,
	0x92, 0x87, 0xf0, 0x2e, 0xaa, 0xea, 0xe0, 0x10, 0x58, 0xd0, 0x94, 0x55, 0xbd, 0x8a, 0x0e, 0x3c,
	0xa3, 0x73, 0xe6, 0xfc, 0x5c, 0x44, 0xdb, 0x9f, 0xc2, 0x45, 0x8e, 0x98, 0x76, 0x48, 0x8f, 0x7d,
	0x9b, 0x30, 0xa9, 0xf0, 0x47, 0xc8, 0x92, 0x8c, 0x8a, 0xf1, 0x6c, 0x78, 0xc6, 0xc5, 0x5a, 0x74,
	0x7a, 0x28, 0x35, 0x3c, 0xe7, 0xc2, 0xc7, 0xef, 0xa3, 0x8a, 0xe4, 0x42, 0x0d, 0xbf, 0x61, 0x2f,
	0xd7, 0xe2, 0xcf, 0xd4, 0xea, 0x63, 0xf6, 0x12, 0x3f, 0x40, 0xa6, 0x60, 0xa7, 0x4c, 0x48, 0x96,
	0x01, 0x78, 0xfd, 0x6e, 0x06, 0x9c, 0x87, 0x99, 0x2b, 0x93, 0xe2, 0x6d, 0x54, 0x0a, 0x83, 0x79,
	0xa0, 0x80, 0xbc, 0x9a, 0x97, 0x2e, 0xf0, 0x2d, 0x54, 0xe6, 0x93, 0x89, 0x64, 0x0a, 0x80, 0xaa,
	0x79, 0xd9, 0x0a, 0x3b, 0xa8, 0x26, 0x38, 0x57, 0xc3, 0xa9, 0xe0, 0x49, 0xac, 0x7b, 0xaf, 0x4c,
	0x8a, 0x7b, 0x55, 0xcf, 0xd2, 0xc1, 0x43, 0x1d, 0x3b, 0xf2, 0xf1, 0x5b, 0xa8, 0xb2, 0x4c, 0x9b,
	0x90, 0x36, 0xa7, 0x59, 0xaa, 0x7e, 0xd1, 0xb4, 0x15, 0xc8, 0xe4, 0x4d, 0x77, 0x6b, 0x49, 0x53,
	0x35, 0x8d, 0x67, 0xc0, 0xd4, 0x91, 0x09, 0x15, 0x08, 0x7c, 0x28, 0x5c, 0xd5, 0x2b, 0xeb, 0xe5,
	0x91, 0x8f, 0x1b, 0x2b, 0x5d, 0x6a, 0x41, 0xe6, 0xa2, 0x0f, 0xb7, 0xf3, 0x3e, 0xdc, 0x84, 0x44,
	0xd6, 0x69, 0x6f, 0x5f, 0xe9, 0xb4, 0x5a, 0x7a, 0xf2, 0x95, 0x5e, 0x72, 0x4e, 0xd0, 0xce, 0x95,
	0x8a, 0xca, 0x98, 0x47, 0x92, 0xe1, 0x7b, 0xc8, 0x52, 0x5c, 0xd1, 0x70, 0x08, 0x03, 0x12, 0x4a,
	0x5a, 0xf3, 0x10, 0x84, 0x9e, 0xe8, 0x08, 0x7e, 0x07, 0x95, 0xf4, 0xe3, 0xa5, 0x5d, 0x00, 0xbc,
	0x6a, 0x97, 0xf1, 0x4a, 0x73, 0xce, 0xef, 0x06, 0xfa, 0xdf, 0x21, 0x53, 0x10, 0xca, 0x58, 0x39,
	0xbd, 0x3c, 0xc5, 0xaa, 0x83, 0x93, 0x45, 0xff, 0xc5, 0x72, 0x4e, 0x7d, 0x67, 0x18, 0x3f, 0x1a,
	0xc7, 0x5f, 0xd3, 0xd6, 0xa4, 0xdf, 0x7a, 0xda, 0x6d, 0x3d, 0x3e, 0x79, 0xf5, 0xe8, 0xbc, 0xb5,
	0xba, 0x7c, 0x70, 0x93, 0x65, 0xcf, 0x3d, 0x5f, 0xde, 0xf7, 0x87, 0xc8, 0x9a, 0x84, 0x9c, 0xaa,
	0x74, 0xf6, 0x01, 0x67, 0x85, 0xc1, 0xee, 0xa2, 0x6f, 0xbb, 0x5b, 0x4f, 0x75, 0x9c, 0x40, 0x9c,
	0x4c, 0x02, 0x16, 0xfa, 0x07, 0xc5, 0x6e, 0xdb, 0xf5, 0x10, 0xe8, 0x01, 0x9e, 0x83, 0xc6, 0xa2,
	0x5f, 0x77, 0x77, 0xf0, 0xff, 0x5f, 0x11, 0x27, 0x3b, 0xbd, 0x73, 0x40, 0x1c, 0xd7, 0x75, 0xc8,
	0xb9, 0xf3, 0xba, 0x80, 0xb6, 0x9e, 0x40, 0xd3, 0xae, 0xfe, 0xce, 0xe5, 0x68, 0x34, 0xfe, 0xfd,
	0x68, 0x2c, 0xdc, 0x74, 0x34, 0x7e, 0x86, 0x2a, 0x31, 0x95, 0x12, 0xba, 0x70, 0x8d, 0x91, 0x3c,
	0xa8, 0x2f, 0xfa, 0xdb, 0x6e, 0x0d, 0xee, 0x3e, 0xf7, 0xc1, 0x9b, 0xc2, 0x5b, 0x6e, 0x83, 0x1f,
	0x5e, 0xf0, 0xb8, 0xce, 0xa4, 0xce, 0x69, 0xfd, 0x8f, 0x43, 0xda, 0x39, 0x46, 0x78, 0xf5, 0x4e,
	0x33, 0x2a, 0x1f, 0xde, 0xe8, 0x15, 0x98, 0xd7, 0xde, 0xfd, 0xd3, 0x40, 0x66, 0x3f, 0x7d, 0xd5,
	0xe3, 0x5f, 0x0d, 0x54, 0xbb, 0x84, 0x3c, 0xbe, 0xb3, 0x44, 0xf7, 0xef, 0x86, 0x5b, 0xe3, 0xee,
	0x3f, 0xa5, 0xd3, 0x33, 0x39, 0x3f, 0x18, 0x8b, 0xfe, 0xec, 0x62, 0xff, 0x93, 0x43, 0xa6, 0x08,
	0xd0, 0xdf, 0x24, 0x93, 0x20, 0x54, 0x4c, 0x90, 0xb3, 0x40, 0xcd, 0x52, 0xb0, 0xe4, 0x5e, 0x76,
	0xfc, 0x26, 0x81, 0x8a, 0x37, 0xc9, 0x6a, 0xbd, 0x9b, 0x24, 0x9d, 0x01, 0xef, 0x36, 0x89, 0xcf,
	0x26, 0x34, 0x09, 0x15, 0x11, 0x4c, 0x25, 0x22, 0x22, 0x34, 0x0c, 0xd3, 0x3d, 0xbf, 0xff, 0xe5,
	0x8f, 0x9f, 0x0a, 0x75, 0xbc, 0xd3, 0x19, 0xeb, 0xbf, 0x16, 0x01, 0x9d, 0xb7, 0x03, 0xde, 0x39,
	0xed, 0x75, 0x20, 0x39, 0xd8, 0x78, 0x51, 0x88, 0x47, 0xa3, 0x32, 0xdc, 0xc5, 0xfe, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x57, 0x99, 0x55, 0xb2, 0xde, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	// Get users, filter with fields(user_id, email, phone_number, status), default return all users
	DescribeUsers(ctx context.Context, in *DescribeUsersRequest, opts ...grpc.CallOption) (*DescribeUsersResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) DescribeUsers(ctx context.Context, in *DescribeUsersRequest, opts ...grpc.CallOption) (*DescribeUsersResponse, error) {
	out := new(DescribeUsersResponse)
	err := c.cc.Invoke(ctx, "/hal9000.Account/DescribeUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	// Get users, filter with fields(user_id, email, phone_number, status), default return all users
	DescribeUsers(context.Context, *DescribeUsersRequest) (*DescribeUsersResponse, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) DescribeUsers(ctx context.Context, req *DescribeUsersRequest) (*DescribeUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeUsers not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_DescribeUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).DescribeUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hal9000.Account/DescribeUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).DescribeUsers(ctx, req.(*DescribeUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hal9000.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeUsers",
			Handler:    _Account_DescribeUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
