// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DescribeUsersRequest struct {
	// query key, support these fields(user_id, email, phone_number, status)
	SearchWord *wrappers.StringValue `protobuf:"bytes,1,opt,name=search_word,json=searchWord,proto3" json:"search_word,omitempty"`
	// sort key, order by sort_key, default create_time
	SortKey *wrappers.StringValue `protobuf:"bytes,2,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	// value = 0 sort ASC, value = 1 sort DESC
	Reverse *wrappers.BoolValue `protobuf:"bytes,3,opt,name=reverse,proto3" json:"reverse,omitempty"`
	// data limit, default 20, max 200
	Limit uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// data offset, default 0
	Offset uint32 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	// use root group ids to get all group ids
	RootGroupId []string `protobuf:"bytes,6,rep,name=root_group_id,json=rootGroupId,proto3" json:"root_group_id,omitempty"`
	// group ids
	GroupId []string `protobuf:"bytes,7,rep,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// user ids
	UserId []string `protobuf:"bytes,8,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// status eg.[active|deleted]
	Status []string `protobuf:"bytes,9,rep,name=status,proto3" json:"status,omitempty"`
	// role ids
	RoleId []string `protobuf:"bytes,10,rep,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// username
	Username []string `protobuf:"bytes,11,rep,name=username,proto3" json:"username,omitempty"`
	// email, eg.op@yunify.com
	Email []string `protobuf:"bytes,12,rep,name=email,proto3" json:"email,omitempty"`
	// phone number, string of 11 digital
	PhoneNumber          []string `protobuf:"bytes,13,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeUsersRequest) Reset()         { *m = DescribeUsersRequest{} }
func (m *DescribeUsersRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeUsersRequest) ProtoMessage()    {}
func (*DescribeUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *DescribeUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeUsersRequest.Unmarshal(m, b)
}
func (m *DescribeUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeUsersRequest.Marshal(b, m, deterministic)
}
func (m *DescribeUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeUsersRequest.Merge(m, src)
}
func (m *DescribeUsersRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeUsersRequest.Size(m)
}
func (m *DescribeUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeUsersRequest proto.InternalMessageInfo

func (m *DescribeUsersRequest) GetSearchWord() *wrappers.StringValue {
	if m != nil {
		return m.SearchWord
	}
	return nil
}

func (m *DescribeUsersRequest) GetSortKey() *wrappers.StringValue {
	if m != nil {
		return m.SortKey
	}
	return nil
}

func (m *DescribeUsersRequest) GetReverse() *wrappers.BoolValue {
	if m != nil {
		return m.Reverse
	}
	return nil
}

func (m *DescribeUsersRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DescribeUsersRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DescribeUsersRequest) GetRootGroupId() []string {
	if m != nil {
		return m.RootGroupId
	}
	return nil
}

func (m *DescribeUsersRequest) GetGroupId() []string {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *DescribeUsersRequest) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *DescribeUsersRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeUsersRequest) GetRoleId() []string {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *DescribeUsersRequest) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *DescribeUsersRequest) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *DescribeUsersRequest) GetPhoneNumber() []string {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type DescribeUsersResponse struct {
	// total count of qualified user
	TotalCount uint32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// list of user
	UserSet              []*User  `protobuf:"bytes,2,rep,name=user_set,json=userSet,proto3" json:"user_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeUsersResponse) Reset()         { *m = DescribeUsersResponse{} }
func (m *DescribeUsersResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeUsersResponse) ProtoMessage()    {}
func (*DescribeUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *DescribeUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeUsersResponse.Unmarshal(m, b)
}
func (m *DescribeUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeUsersResponse.Marshal(b, m, deterministic)
}
func (m *DescribeUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeUsersResponse.Merge(m, src)
}
func (m *DescribeUsersResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeUsersResponse.Size(m)
}
func (m *DescribeUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeUsersResponse proto.InternalMessageInfo

func (m *DescribeUsersResponse) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DescribeUsersResponse) GetUserSet() []*User {
	if m != nil {
		return m.UserSet
	}
	return nil
}

type User struct {
	// user id, user belong to different group and role, has different permissions
	UserId *wrappers.StringValue `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// user name
	Username *wrappers.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// user email
	Email *wrappers.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// user phone number
	PhoneNumber *wrappers.StringValue `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// user description
	Description *wrappers.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// user status eg.[active|deleted]
	Status *wrappers.StringValue `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// the time when user create
	CreateTime *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// the time when user update
	UpdateTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// record changed time of status
	StatusTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *User) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *User) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetPhoneNumber() *wrappers.StringValue {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *User) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *User) GetStatus() *wrappers.StringValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *User) GetStatusTime() *timestamp.Timestamp {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type CreateUserRequest struct {
	// required, user email
	Email *wrappers.StringValue `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// user phone number
	PhoneNumber *wrappers.StringValue `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// required, user password
	Password *wrappers.StringValue `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// required, user role_id
	RoleId *wrappers.StringValue `protobuf:"bytes,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// user description
	Description          *wrappers.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CreateUserRequest) GetPhoneNumber() *wrappers.StringValue {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *CreateUserRequest) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *CreateUserRequest) GetRoleId() *wrappers.StringValue {
	if m != nil {
		return m.RoleId
	}
	return nil
}

func (m *CreateUserRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

type CreateUserResponse struct {
	// id of user created
	UserId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func init() {
	proto.RegisterType((*DescribeUsersRequest)(nil), "hal9000.DescribeUsersRequest")
	proto.RegisterType((*DescribeUsersResponse)(nil), "hal9000.DescribeUsersResponse")
	proto.RegisterType((*User)(nil), "hal9000.User")
	proto.RegisterType((*CreateUserRequest)(nil), "hal9000.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "hal9000.CreateUserResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 791 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xeb, 0x44,
	0x14, 0x55, 0x3e, 0x5e, 0x3e, 0xc6, 0x2f, 0x48, 0x8c, 0x1e, 0x60, 0xc2, 0xe3, 0xbd, 0xc1, 0xab,
	0x50, 0xb9, 0x49, 0x09, 0x45, 0x14, 0x10, 0xa0, 0xb6, 0x48, 0x55, 0x55, 0x89, 0x45, 0x5a, 0x40,
	0x42, 0x42, 0xd6, 0x24, 0xbe, 0x71, 0x46, 0xd8, 0x1e, 0x33, 0x33, 0x6e, 0xd4, 0x2d, 0x4b, 0x96,
	0x65, 0xc5, 0x4f, 0x61, 0xcd, 0x1f, 0x40, 0x62, 0xc5, 0x9e, 0x1f, 0x82, 0x66, 0xc6, 0x76, 0x42,
	0x3f, 0x54, 0xd3, 0xb7, 0x4a, 0xee, 0xb9, 0xf7, 0x78, 0xee, 0x9c, 0x7b, 0xee, 0x20, 0xa4, 0x40,
	0xaa, 0x71, 0x26, 0xb8, 0xe2, 0xb8, 0xbb, 0xa2, 0xf1, 0x27, 0x7b, 0x7b, 0x7b, 0xc3, 0x17, 0x11,
	0xe7, 0x51, 0x0c, 0x13, 0x03, 0xcf, 0xf3, 0xe5, 0x64, 0x2d, 0x68, 0x96, 0x81, 0x90, 0xb6, 0x70,
	0xf8, 0xf2, 0x66, 0x5e, 0xb1, 0x04, 0xa4, 0xa2, 0x49, 0x56, 0x14, 0x3c, 0x2f, 0x0a, 0x68, 0xc6,
	0x26, 0x34, 0x4d, 0xb9, 0xa2, 0x8a, 0xf1, 0xb4, 0xa4, 0xfb, 0xe6, 0x67, 0xb1, 0x1b, 0x41, 0xba,
	0x2b, 0xd7, 0x34, 0x8a, 0x40, 0x4c, 0x78, 0x66, 0x2a, 0x6e, 0x57, 0x7b, 0x7f, 0xb6, 0xd0, 0xb3,
	0xaf, 0x40, 0x2e, 0x04, 0x9b, 0xc3, 0x37, 0x12, 0x84, 0x9c, 0xc1, 0x4f, 0x39, 0x48, 0x85, 0x3f,
	0x47, 0x8e, 0x04, 0x2a, 0x16, 0xab, 0x60, 0xcd, 0x45, 0xe8, 0x36, 0x48, 0x63, 0xe4, 0x4c, 0x9f,
	0x8f, 0xed, 0xd1, 0xe3, 0xb2, 0xb7, 0xf1, 0xb9, 0x12, 0x2c, 0x8d, 0xbe, 0xa5, 0x71, 0x0e, 0x33,
	0x64, 0x09, 0xdf, 0x71, 0x11, 0xe2, 0x8f, 0x51, 0x4f, 0x72, 0xa1, 0x82, 0x1f, 0xe1, 0xca, 0x6d,
	0xd6, 0xe0, 0x76, 0x75, 0xf5, 0x19, 0x5c, 0xe1, 0x7d, 0xd4, 0x15, 0x70, 0x09, 0x42, 0x82, 0xdb,
	0x32, 0xbc, 0xe1, 0x2d, 0xde, 0x11, 0xe7, 0x71, 0xc1, 0x2a, 0x4a, 0xf1, 0x33, 0xf4, 0x24, 0x66,
	0x09, 0x53, 0x6e, 0x9b, 0x34, 0x46, 0x83, 0x99, 0x0d, 0xf0, 0x9b, 0xa8, 0xc3, 0x97, 0x4b, 0x09,
	0xca, 0x7d, 0x62, 0xe0, 0x22, 0xc2, 0x1e, 0x1a, 0x08, 0xce, 0x55, 0x10, 0x09, 0x9e, 0x67, 0x01,
	0x0b, 0xdd, 0x0e, 0x69, 0x8d, 0xfa, 0x33, 0x47, 0x83, 0x27, 0x1a, 0x3b, 0x0d, 0xf1, 0xdb, 0xa8,
	0x57, 0xa5, 0xbb, 0x26, 0xdd, 0x8d, 0x8a, 0xd4, 0x5b, 0xa8, 0x9b, 0x4b, 0x10, 0x3a, 0xd3, 0x33,
	0x99, 0x8e, 0x0e, 0x4f, 0x43, 0x7d, 0x9e, 0x54, 0x54, 0xe5, 0xd2, 0xed, 0x5b, 0xdc, 0x46, 0x9a,
	0x20, 0x78, 0x0c, 0x9a, 0x80, 0x6c, 0x42, 0x87, 0xa7, 0x21, 0x1e, 0xa2, 0x9e, 0xa6, 0xa6, 0x34,
	0x01, 0xd7, 0x31, 0x99, 0x2a, 0xd6, 0x57, 0x82, 0x84, 0xb2, 0xd8, 0x7d, 0x6a, 0x12, 0x36, 0xc0,
	0xef, 0xa1, 0xa7, 0xd9, 0x8a, 0xa7, 0x10, 0xa4, 0x79, 0x32, 0x07, 0xe1, 0x0e, 0x6c, 0xe7, 0x06,
	0xfb, 0xda, 0x40, 0xde, 0x1c, 0xbd, 0x71, 0x63, 0xa2, 0x32, 0xe3, 0xa9, 0x04, 0xfc, 0x12, 0x39,
	0x8a, 0x2b, 0x1a, 0x07, 0x0b, 0x9e, 0xa7, 0xca, 0x8c, 0x74, 0x30, 0x43, 0x06, 0x3a, 0xd6, 0x08,
	0x1e, 0xd9, 0x76, 0x02, 0xad, 0x58, 0x93, 0xb4, 0x46, 0xce, 0x74, 0x30, 0x2e, 0x5c, 0x3b, 0xd6,
	0x9f, 0x9a, 0x99, 0x7b, 0x9f, 0x83, 0xf2, 0x7e, 0x6b, 0xa3, 0xb6, 0x46, 0xf0, 0x47, 0x1b, 0x2d,
	0xea, 0x58, 0xa4, 0x54, 0xea, 0x60, 0xeb, 0xe2, 0x75, 0xec, 0xb1, 0x91, 0x65, 0x5a, 0xca, 0xd2,
	0xaa, 0x41, 0x2b, 0x44, 0xfb, 0xf2, 0x86, 0x68, 0xed, 0x1a, 0xd4, 0x6d, 0x49, 0xf1, 0x17, 0xc8,
	0x09, 0x8d, 0xa4, 0x66, 0x8f, 0x8c, 0x9b, 0x1e, 0xe4, 0x6f, 0x11, 0xf0, 0x7e, 0x65, 0x8c, 0x4e,
	0x1d, 0x91, 0x0a, 0xdb, 0x7c, 0x86, 0x9c, 0x85, 0x00, 0xaa, 0x20, 0xd0, 0x2f, 0x80, 0xdb, 0xbd,
	0x67, 0x1d, 0x2e, 0xca, 0xe7, 0x61, 0x86, 0x6c, 0xb9, 0x06, 0x34, 0x39, 0xcf, 0xc2, 0x8a, 0xdc,
	0x7b, 0x98, 0x6c, 0xcb, 0x4b, 0xb2, 0xed, 0xc1, 0x92, 0xfb, 0x0f, 0x93, 0x6d, 0xb9, 0x06, 0xbc,
	0xdf, 0x9b, 0xe8, 0xf5, 0x63, 0xd3, 0x88, 0xf1, 0x4c, 0xf1, 0x9e, 0x54, 0x73, 0x6b, 0x3c, 0x7e,
	0x6e, 0xcd, 0xff, 0x3b, 0xb7, 0x03, 0xd4, 0xcb, 0xa8, 0x94, 0xe6, 0x05, 0xab, 0xe3, 0x97, 0xaa,
	0x5a, 0xfb, 0xba, 0x5c, 0xd9, 0x3a, 0x6e, 0x29, 0x17, 0xfa, 0x15, 0x8d, 0xe2, 0x9d, 0x21, 0xbc,
	0x2d, 0x5d, 0xb1, 0xb8, 0x8f, 0x5b, 0xb2, 0xe9, 0xdf, 0x4d, 0xd4, 0xbe, 0xd0, 0xda, 0xff, 0xd1,
	0x40, 0x83, 0xff, 0x3c, 0x09, 0xf8, 0xdd, 0x6a, 0xaf, 0xef, 0x7a, 0xfc, 0x87, 0x2f, 0xee, 0x4b,
	0xdb, 0x86, 0x3c, 0x79, 0x7d, 0x18, 0xe0, 0x1f, 0x4e, 0x40, 0x11, 0x7d, 0x94, 0xf4, 0xc9, 0x92,
	0xc5, 0x0a, 0x04, 0x59, 0x33, 0xb5, 0x22, 0x4b, 0x06, 0x71, 0x28, 0x47, 0x45, 0xc7, 0x3e, 0x31,
	0xb3, 0xf4, 0xc9, 0xf6, 0x24, 0x7d, 0x62, 0xfd, 0xf2, 0xbe, 0x4f, 0x42, 0x58, 0xd2, 0x3c, 0x56,
	0x44, 0x80, 0xca, 0x45, 0x4a, 0x68, 0x1c, 0xdb, 0x6f, 0xfe, 0xfc, 0xd7, 0x3f, 0xbf, 0x36, 0x1d,
	0xdc, 0x9f, 0x5c, 0x7e, 0x30, 0x31, 0x00, 0xfe, 0xa5, 0x81, 0xd0, 0x46, 0x1c, 0x3c, 0xac, 0x7a,
	0xbc, 0x65, 0xb6, 0xe1, 0x3b, 0x77, 0xe6, 0x8a, 0xe6, 0x8f, 0xaf, 0x0f, 0x7d, 0xbc, 0x63, 0x13,
	0xe6, 0x2c, 0x9f, 0xb0, 0xa5, 0xf9, 0x43, 0x56, 0xf4, 0x12, 0x08, 0x0d, 0x13, 0x96, 0x92, 0x0c,
	0x44, 0xc2, 0xa4, 0x64, 0x3c, 0x35, 0x9d, 0xbc, 0xe6, 0x6d, 0x3a, 0xf9, 0xb4, 0xb1, 0x73, 0xd4,
	0xfe, 0xbe, 0x99, 0xcd, 0xe7, 0x1d, 0xa3, 0xff, 0x87, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0f,
	0xa5, 0x0e, 0x98, 0xe8, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	// Get users, filter with fields(user_id, email, phone_number, status), default return all users
	DescribeUsers(ctx context.Context, in *DescribeUsersRequest, opts ...grpc.CallOption) (*DescribeUsersResponse, error)
	// Create user, if user have admin permission
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) DescribeUsers(ctx context.Context, in *DescribeUsersRequest, opts ...grpc.CallOption) (*DescribeUsersResponse, error) {
	out := new(DescribeUsersResponse)
	err := c.cc.Invoke(ctx, "/hal9000.Test/DescribeUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/hal9000.Test/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	// Get users, filter with fields(user_id, email, phone_number, status), default return all users
	DescribeUsers(context.Context, *DescribeUsersRequest) (*DescribeUsersResponse, error)
	// Create user, if user have admin permission
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) DescribeUsers(ctx context.Context, req *DescribeUsersRequest) (*DescribeUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeUsers not implemented")
}
func (*UnimplementedTestServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_DescribeUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).DescribeUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hal9000.Test/DescribeUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).DescribeUsers(ctx, req.(*DescribeUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hal9000.Test/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hal9000.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeUsers",
			Handler:    _Test_DescribeUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Test_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
